const data = {
  defaultPointsDisplayed: [
    "Gare de Charleville",
    "Gonzague",
    "Place Ducale",
    "Hôtel de Ville",
    "CHU Manchester",
  ],
  lines: [{
      start: "Place Ducale",
      end: "Gare de Charleville",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Gonzague",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Pont de Montcy",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Place des Droits de l’Homme",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Cimetière Boutet",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Gare de Charleville",
      end: "Pont de Montcy",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Gare de Charleville",
      end: "Hôtel de Ville",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Gonzague",
      end: "Hôtel de Ville",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Gonzague",
      end: "Bd Gambetta",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Pont de Montcy",
      end: "Parc du Mont Olympe",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Pont de Montcy",
      end: "Montcy-Saint-Pierre",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Pont de Montcy",
      end: "Pont D58",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Cimetière Boutett",
      difficulty: 1,
      displayMin: true,
      time: 4,
      times: { hard: 5, easy: 3 },
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Parc Collignon",
      difficulty: 1,
      displayMin: true,
      time: 4,
      times: { hard: 5, easy: 3 },
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Bel-Air",
      difficulty: 1,
      displayMin: true,
      time: 8,
      times: { hard: 11, easy: 4 },
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Montcy-Notre-Dame",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 11, easy: 9 },
      align: "top",
    },
    {
      start: "Cimetière Boutet",
      end: "Bd Gambetta",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Cimetière Boutet",
      end: "Etion",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Cimetière Boutet",
      end: "Parc Collignon",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Bd Gambetta",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "CHU Manchester",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Parc des expos",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Ronde Couture",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Gare de Mohon",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Romery",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Le Theux",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 12, easy: 8 },
      align: "bottom",
    },
    {
      start: "Hôtel de Ville",
      end: "Pont D58",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Bd Gambetta",
      end: "N43",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Parc du Mont Olympe",
      end: "Montcy-Saint-Pierre",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Montcy-Saint-Pierre",
      end: "Pont D58",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Montcy-Saint-Pierre",
      end: "Mairie de Montcy-Notre-Dame",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Pont D58",
      end: "Mairie de Montcy-Notre-Dame",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "bottom",
    },
    {
      start: "Pont D58",
      end: "Aiglemont",
      difficulty: 1,
      displayMin: true,
      time: 14,
      times: { hard: 18, easy: 9 },
      align: "bottom",
    },
    {
      start: "Pont D58",
      end: "Le Theux",
      difficulty: 1,
      displayMin: true,
      time: 11,
      times: { hard: 12, easy: 9 },
      align: null,
    },
    {
      start: "Parc Collignon",
      end: "N43",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "bottom",
    },
    {
      start: "Parc Collignon",
      end: "Etion",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "bottom",
    },
    {
      start: "Parc Collignon",
      end: "La Havetière",
      difficulty: 1,
      displayMin: true,
      time: 8,
      times: { hard: 10, easy: 6 },
      align: "bottom",
    },
    {
      start: "Parc Collignon",
      end: "Bel-Air",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Bel-Air",
      end: "La Havetière",
      difficulty: 1,
      displayMin: true,
      time: 9,
      times: { hard: 10, easy: 8 },
      align: "top",
    },
    {
      start: "Bel-Air",
      end: "La Culbute",
      difficulty: 1,
      displayMin: true,
      time: 4,
      times: { hard: 4, easy: 3 },
      align: null,
    },
    {
      start: "Bel-Air",
      end: "Pont de Nouzonville",
      difficulty: 1,
      displayMin: true,
      time: 23,
      times: { hard: 26, easy: 19 },
      align: "bottom",
    },
    {
      start: "Montcy-Notre-Dame",
      end: "Mairie de Montcy-Notre-Dame",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Etion",
      end: "N43",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: null,
    },
    {
      start: "Etion",
      end: "Damouzy",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "CHU Manchester",
      end: "La Warenne",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "bottom",
    },
    {
      start: "CHU Manchester",
      end: "Mairie de Warcq",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "bottom",
    },
    {
      start: "Parc des expos",
      end: "Gare de Mohon",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Parc des expos",
      end: "Ronde Couture",
      difficulty: 0,
      displayMin: false,
      time: 7,
      align: null,
    },
    {
      start: "Parc des expos",
      end: "[Lotissement random point externe]",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Parc des expos",
      end: "Mairie de Prix-lès-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Ronde Couture",
      end: "[Lotissement random point externe]",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Ronde Couture",
      end: "Centre Commercial La Croisette",
      difficulty: 0,
      displayMin: false,
      time: 9,
      times: { hard: 9, easy: 8 },
      align: null,
    },
    {
      start: "Ronde Couture",
      end: "Campus Sup Ardennes",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Ronde Couture",
      end: "Gare de Mohon",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Gare de Mohon",
      end: "Campus Sup Ardennes",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Gare de Mohon",
      end: "Pont Voie Ferrée",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Gare de Mohon",
      end: "Semeuse",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Romery",
      end: "Le Theux",
      difficulty: 1,
      displayMin: true,
      time: 13,
      times: { hard: 14, easy: 11 },
      align: null,
    },
    {
      start: "Romery",
      end: "Saint Laurent",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 14, easy: 6 },
      align: null,
    },
    {
      start: "Le Theux",
      end: "Saint Laurent",
      difficulty: 1,
      displayMin: true,
      time: 10,
      times: { hard: 12, easy: 7 },
      align: "top",
    },
    {
      start: "N43",
      end: "Mairie de Warcq",
      difficulty: 1,
      displayMin: true,
      time: 7,
      times: { hard: 7, easy: 6 },
      align: null,
    },
    {
      start: "Mairie de Montcy-Notre-Dame",
      end: "Pont de Nouzonville",
      difficulty: 0,
      displayMin: true,
      time: 24,
      align: "bottom",
    },
    {
      start: "Aiglemont",
      end: "Saint Laurent",
      difficulty: 0,
      displayMin: false,
      time: 10,
      align: "bottom",
    },
    {
      start: "Aiglemont",
      end: "Gare de Nouzonville",
      difficulty: 1,
      displayMin: true,
      time: 19,
      times: { hard: 23, easy: 15 },
      align: null,
    },
    {
      start: "Gare de Nouzonville",
      end: "Pont de Nouzonville",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "bottom",
    },
    {
      start: "La Havetière",
      end: "La Culbute",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "bottom",
    },
    {
      start: "La Warenne",
      end: "Mairie de Warcq",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Mairie de Warcq",
      end: "Mairie de Prix-lès-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Centre Commercial La Croisette",
      end: "Campus Sup Ardennes",
      difficulty: 1,
      displayMin: true,
      time: 6,
      times: { hard: 6, easy: 5 },
      align: "top",
    },
    {
      start: "Campus Sup Ardennes",
      end: "Mairie de La Francheville",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Pont Voie Ferrée",
      end: "Mairie de Villers-Semeuse",
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Pont Voie Ferrée",
      end: "ZI de Charleville-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Semeuse",
      end: "Mairie de Villers-Semeuse",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Mairie de Villers-Semeuse",
      end: "ZI de Charleville-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Mairie de Villers-Semeuse",
      end: "Centre Commercial CORA",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: null,
    },
    {
      start: "Les Ayvelles",
      end: "Centre Commercial CORA",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Fort des Ayvelles",
      end: "Mairie de Villers-Semeuse",
      difficulty: 1,
      displayMin: true,
      time: 12,
      times: { hard: 13, easy: 10 },
      align: null,
    },
    {
      start: "Fort des Ayvelles",
      end: "Mairie de La Francheville",
      difficulty: 1,
      displayMin: true,
      time: 7,
      times: { hard: 8, easy: 5 },
      align: null,
    },
    {
      start: "Fort des Ayvelles",
      end: "Les Ayvelles",
      difficulty: 1,
      displayMin: true,
      time: 13,
      times: { hard: 15, easy: 11 },
      align: null,
    },
  ],
  points: {
    "Gare de Charleville": { x: 993, y: 582 },
    Gonzague: { x: 562, y: 654 },
    "Place Ducale": { x: 580, y: 467 },
    "Pont de Montcy": { x: 775, y: 646 },
    "Parc du Mont Olympe": { x: 693, y: 471 },
    "Montcy-Saint-Pierre": { x: 534, y: 583 },
    "Pont D58": {x: 647, y: 618},
    "Place des Droits de l’Homme": { x: 813, y: 372 },
    "Bel-Air": { x: 405, y: 612 },
    "La Culbute": { x: 634, y: 424 },
    "La Havetière": { x: 841, y: 634 },
    "Parc Collignon": {x: 663, y: 566},
    "Cimetière Boutet": { x: 809, y: 481 },
    "Etion": { x: 607, y: 714 },
    "Bd Gambetta": { x: 742, y: 606 },
    "La Warenne": { x: 567, y: 535 },
    "CHU Manchester": { x: 724, y: 524 },
    "Hôtel de Ville":  {x: 793, y: 586},
    "Parc des expos": { x: 471, y: 493 },
    "Gare de Mohon": { x: 695, y: 732 },
    "Ronde Couture": { x: 885, y: 706 },
    "Campus Sup Ardennes": { x: 417, y: 465 },
    "Centre Commercial La Croisette": { x: 891, y: 544 },
    "[Lotissement random point externe]": { x: 826, y: 743 },
    "ZI de Charleville-Mézières": { x: 535, y: 372 },
    "Pont Voie Ferrée": { x: 339, y: 685 },
    "Le Theux": { x: 708, y: 351 },
    "Romery": { x: 887, y: 468 },
    "Saint Laurent": { x: 580, y: 775 },
    "Aiglemont": { x: 810, y: 551 },
    "Pont de Nouzonville": { x: 471, y: 582 },
    "Gare de Nouzonville": { x: 700, y: 142 },
    "Mairie de Montcy-Notre-Dame": { x: 599, y: 138 },
    "Montcy-Notre-Dame": { x: 617, y: 268 },
    "N43": { x: 597, y: 356 },
    "Mairie de Warcq": { x: 934, y: 813 },
    "Damouzy": { x: 710, y: 796 },
    "Mairie de Prix-lès-Mézières": { x: 721, y: 947 },
    "Mairie de La Francheville": { x: 278, y: 398 },
    "Les Ayvelles": { x: 512, y: 333 },
    "Centre Commercial CORA": { x: 568, y: 315 },
    "Mairie de Villers-Semeuse": { x: 462, y: 285 },
    "Semeuse": { x: 703, y: 255 },
    "Fort des Ayvelles": { x: 491, y: 536 },
  },
};
