const data = {
  defaultPointsDisplayed: [
    "Gare de Charleville",
    "Pont de Nouzonville",
    "Mairie de Villers-Semeuse",
    "Place Ducale",
    "Hôtel de Ville",
    "CHU Manchester",
    "Aiglemont",
    "Saint Laurent",
    "Mairie de Prix-lès-Mézières",
    "Mairie de La Francheville",
    "Les Ayvelles",
    "Mairie de Montcy-Notre-Dame",
    "Mairie de Warcq",
    "Damouzy",
  ],
  lines: [{
      start: "Place Ducale",
      end: "Gare de Charleville",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Gonzague",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Pont de Montcy",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Place des Droits de l’Homme",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Place Ducale",
      end: "Cimetière Boutet",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Gare de Charleville",
      end: "Pont de Montcy",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
          {
      start: "Gare de Charleville",
      end: "Gonzague",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "top",
    },
    {
      start: "Gare de Charleville",
      end: "Hôtel de Ville",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Gonzague",
      end: "Hôtel de Ville",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Gonzague",
      end: "Bd Gambetta",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Pont de Montcy",
      end: "Parc du Mont Olympe",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Pont de Montcy",
      end: "Montcy-Saint-Pierre",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Pont de Montcy",
      end: "Pont D58",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Cimetière Boutet",
      difficulty: 1,
      displayMin: true,
      time: 4,
      times: { hard: 5, easy: 3 },
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Parc Collignon",
      difficulty: -1,
      displayMin: true,
      time: 4,
      times: { hard: 5, easy: 3 },
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Bel-Air",
      difficulty: -1,
      displayMin: true,
      time: 8,
      times: { hard: 11, easy: 4 },
      align: "top",
    },
    {
      start: "Place des Droits de l’Homme",
      end: "Montcy-Notre-Dame",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 11, easy: 9 },
      align: "top",
    },
    {
      start: "Cimetière Boutet",
      end: "Bd Gambetta",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Cimetière Boutet",
      end: "Etion",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Cimetière Boutet",
      end: "Parc Collignon",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Bd Gambetta",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "CHU Manchester",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Parc des expos",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Ronde Couture",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Gare de Mohon",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Romery",
      difficulty: 0,
      displayMin: true,
      time: 17,
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Le Theux",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 12, easy: 8 },
      align: "top",
    },
    {
      start: "Hôtel de Ville",
      end: "Pont D58",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },
    {
      start: "Bd Gambetta",
      end: "N43",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Parc du Mont Olympe",
      end: "Montcy-Saint-Pierre",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Montcy-Saint-Pierre",
      end: "Pont D58",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Montcy-Saint-Pierre",
      end: "Mairie de Montcy-Notre-Dame",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Pont D58",
      end: "Mairie de Montcy-Notre-Dame",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "top",
    },
    {
      start: "Pont D58",
      end: "Aiglemont",
      difficulty: -1,
      displayMin: true,
      time: 14,
      times: { hard: 18, easy: 9 },
      align: "top",
    },
    {
      start: "Pont D58",
      end: "Le Theux",
      difficulty: 1,
      displayMin: true,
      time: 11,
      times: { hard: 12, easy: 9 },
      align: "top",
    },
    {
      start: "Parc Collignon",
      end: "N43",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Parc Collignon",
      end: "Etion",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Parc Collignon",
      end: "La Havetière",
      difficulty: -1,
      displayMin: true,
      time: 8,
      times: { hard: 10, easy: 6 },
      align: "top",
    },
    {
      start: "Parc Collignon",
      end: "Bel-Air",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Bel-Air",
      end: "La Havetière",
      difficulty: -1,
      displayMin: true,
      time: 9,
      times: { hard: 10, easy: 8 },
      align: "top",
    },
    {
      start: "Bel-Air",
      end: "La Culbute",
      difficulty: -1,
      displayMin: true,
      time: 4,
      times: { hard: 4, easy: 3 },
      align: "top",
    },
    {
      start: "Bel-Air",
      end: "Pont de Nouzonville",
      difficulty: 1,
      displayMin: true,
      time: 23,
      times: { hard: 26, easy: 19 },
      align: "top",
    },
    {
      start: "Montcy-Notre-Dame",
      end: "Mairie de Montcy-Notre-Dame",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Etion",
      end: "N43",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Etion",
      end: "Damouzy",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "CHU Manchester",
      end: "La Warenne",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "CHU Manchester",
      end: "Mairie de Warcq",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Parc des expos",
      end: "Gare de Mohon",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Parc des expos",
      end: "Ronde Couture",
      difficulty: 0,
      displayMin: false,
      time: 7,
      align: "top",
    },
    {
      start: "Parc des expos",
      end: "[Lotissement random point externe]",
      difficulty: 0,
      displayMin: true,
      time: 3,
      align: "top",
    },
    {
      start: "Parc des expos",
      end: "Mairie de Prix-lès-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Ronde Couture",
      end: "[Lotissement random point externe]",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Ronde Couture",
      end: "Centre Commercial La Croisette",
      difficulty: 1,
      displayMin: false,
      time: 9,
      times: { hard: 9, easy: 8 },
      align: "top",
    },
    {
      start: "Ronde Couture",
      end: "Campus Sup Ardennes",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Ronde Couture",
      end: "Gare de Mohon",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Gare de Mohon",
      end: "Campus Sup Ardennes",
      difficulty: 0,
      displayMin: true,
      time: 8,
      align: "top",
    },
    {
      start: "Gare de Mohon",
      end: "Pont Voie Ferrée",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Gare de Mohon",
      end: "Semeuse",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Romery",
      end: "Le Theux",
      difficulty: -1,
      displayMin: true,
      time: 13,
      times: { hard: 14, easy: 11 },
      align: "top",
    },
    {
      start: "Romery",
      end: "Saint Laurent",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 14, easy: 6 },
      align: "top",
    },
    {
      start: "Le Theux",
      end: "Saint Laurent",
      difficulty: -1,
      displayMin: true,
      time: 10,
      times: { hard: 12, easy: 7 },
      align: "top",
    },
    {
      start: "N43",
      end: "Mairie de Warcq",
      difficulty: -1,
      displayMin: true,
      time: 7,
      times: { hard: 7, easy: 6 },
      align: "top",
    },
    {
      start: "Mairie de Montcy-Notre-Dame",
      end: "Pont de Nouzonville",
      difficulty: 0,
      displayMin: true,
      time: 24,
      align: "top",
    },
    {
      start: "Aiglemont",
      end: "Saint Laurent",
      difficulty: 0,
      displayMin: false,
      time: 10,
      align: "top",
    },
    {
      start: "Aiglemont",
      end: "Gare de Nouzonville",
      difficulty: 1,
      displayMin: true,
      time: 19,
      times: { hard: 23, easy: 15 },
      align: "top",
    },
    {
      start: "Gare de Nouzonville",
      end: "Pont de Nouzonville",
      difficulty: 0,
      displayMin: true,
      time: 2,
      align: "top",
    },
    {
      start: "La Havetière",
      end: "La Culbute",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "La Warenne",
      end: "Mairie de Warcq",
      difficulty: 0,
      displayMin: true,
      time: 9,
      align: "top",
    },
    {
      start: "Mairie de Warcq",
      end: "Mairie de Prix-lès-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 18,
      align: "top",
    },
    {
      start: "Centre Commercial La Croisette",
      end: "Campus Sup Ardennes",
      difficulty: 1,
      displayMin: true,
      time: 6,
      times: { hard: 6, easy: 5 },
      align: "top",
    },
    {
      start: "Campus Sup Ardennes",
      end: "Mairie de La Francheville",
      difficulty: 0,
      displayMin: true,
      time: 7,
      align: "top",
    },
    {
      start: "Pont Voie Ferrée",
      end: "Mairie de Villers-Semeuse",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Pont Voie Ferrée",
      end: "ZI de Charleville-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Semeuse",
      end: "Mairie de Villers-Semeuse",
      difficulty: 0,
      displayMin: true,
      time: 4,
      align: "top",
    },
    {
      start: "Mairie de Villers-Semeuse",
      end: "ZI de Charleville-Mézières",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Mairie de Villers-Semeuse",
      end: "Centre Commercial CORA",
      difficulty: 0,
      displayMin: true,
      time: 6,
      align: "top",
    },
    {
      start: "Les Ayvelles",
      end: "Centre Commercial CORA",
      difficulty: 0,
      displayMin: true,
      time: 5,
      align: "top",
    },
    {
      start: "Fort des Ayvelles",
      end: "Mairie de Villers-Semeuse",
      difficulty: 1,
      displayMin: true,
      time: 12,
      times: { hard: 13, easy: 10 },
      align: "top",
    },
    {
      start: "Fort des Ayvelles",
      end: "Mairie de La Francheville",
      difficulty: 1,
      displayMin: true,
      time: 7,
      times: { hard: 8, easy: 5 },
      align: "top",
    },
    {
      start: "Fort des Ayvelles",
      end: "Les Ayvelles",
      difficulty: -1,
      displayMin: true,
      time: 13,
      times: { hard: 15, easy: 11 },
      align: "top",
    },
    {
      start: "Romery",
      end: "Ville-sur-Lumes",
      difficulty: 1,
      displayMin: true,
      time: 7,
      times: { hard: 10, easy: 4 },
      align: "top",
    },
    {
      start: "Ville-sur-Lumes",
      end: "",
      difficulty: 1,
      displayMin: true,
      time: 7,
      times: { hard: 8, easy: 5 },
      align: "top",
    },
    {
      start: "Romery",
      end: "Gare de Lumes",
      difficulty: 0,
      displayMin: true,
      time: 12,
      align: "top",
    },      
  ],
  points: {
    "Gare de Charleville": { x: 570, y: 805 },
    Gonzague: { x: 524, y: 767 },
    "Place Ducale": { x: 536, y: 730 },
    "Pont de Montcy": { x: 600, y: 697 },
    "Parc du Mont Olympe": { x: 531, y: 635 },
    "Montcy-Saint-Pierre": { x: 608, y: 627 },
    "Pont D58": {x: 671, y: 713},
    "Place des Droits de l’Homme": { x: 499, y: 658 },
    "Bel-Air": { x: 546, y: 549 },
    "La Culbute": { x: 585, y: 467 },
    "La Havetière": { x: 466, y: 405 },
    "Parc Collignon": {x: 445, y: 594},
    "Cimetière Boutet": { x: 442, y: 696 },
    "Etion": { x: 310, y: 563 },
    "Bd Gambetta": { x: 396, y: 729 },
    "La Warenne": { x: 197, y: 910 },
    "CHU Manchester": { x: 345, y: 880 },
    "Hôtel de Ville":  {x: 519, y: 914},
    "Parc des expos": { x: 426, y: 962 },
    "Gare de Mohon": { x: 643, y: 1016 },
    "Ronde Couture": { x: 533, y: 1079 },
    "Campus Sup Ardennes": { x: 532, y: 1213 },
    "Centre Commercial La Croisette": { x: 412, y: 1206 },
    "[Lotissement random point externe]": { x: 396, y: 1039 },
    "ZI de Charleville-Mézières": { x: 650, y: 1233 },
    "Pont Voie Ferrée": { x: 662, y: 1132 },
    "Le Theux": { x: 703, y: 914 },
    "Romery": { x: 962, y: 1038 },
    "Saint Laurent": { x: 988, y: 859 },
    "Aiglemont": { x: 938, y: 620 },
    "Pont de Nouzonville": { x: 715, y: 140 },
    "Gare de Nouzonville": { x: 731, y: 202 },
    "Mairie de Montcy-Notre-Dame": { x: 730, y: 724 },
    "Montcy-Notre-Dame": { x: 708, y: 641 },
    "N43": { x: 311, y: 664 },
    "Mairie de Warcq": { x: 179, y: 792 },
    "Damouzy": { x: 138, y: 399 },
    "Mairie de Prix-lès-Mézières": { x: 239, y: 996 },
    "Mairie de La Francheville": { x: 461, y: 1347 },
    "Les Ayvelles": { x: 852, y: 1434 },
    "Centre Commercial CORA": { x: 820, y: 1295 },
    "Mairie de Villers-Semeuse": { x: 767, y: 1156 },
    "Semeuse": { x: 812, y: 1070 },
    "Fort des Ayvelles": { x: 642, y: 1389 },
    "Ville-sur-Lumes": { x: 1122, y: 1006 },
    "La Grandville": { x: 1202, y: 649 },
    "Neufmanil": { x: 1189, y: 226 },
    "Gare de Lumes": { x: 1091, y: 1287 },
    "Houldizy": { x: 86, y: 223 },
    "La Mal Campée": { x: 165, y: 562 },
    
  },
};
